### ISSUE TITLE
AutoSave

### ISSUE THREAD

**Issue by JuanCSUCoder** [JuanCSUCoder/SystemicWorks#22]
**Is your feature request related to a problem? Please describe.**
It is annoying to always have to specify the file location to save

**Describe the solution you'd like**
To specify the file location once and then save it there automaticaly when there are changes made to the model.

**Comment by JCSUCoder** [comment]
This should be moved to another repo, dedicated to the desktop application

**Comment by JuanCSUCoder** [comment]
[Relevant Google Chrome Feature](https://youtu.be/GNuG-5m4Ud0)

**Comment by JuanCSUCoder** [comment]
[Guide to Implement that new feature in production](https://www.thinktecture.com/en/pwa/making-of-paint-js-file-access/#safe-and-secure-file-system-access)

**Comment by JuanCSUCoder** [comment]
This feature will be discarded until the support for FileSystemAccess API became official
